
(()=>{
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const root=$('.cinema'), scenes=$$('.scene'), nav=$$('[data-go]');
let current=0,locked=false;
function go(i){i=Math.max(0,Math.min(scenes.length-1,i));scenes[i].scrollIntoView({behavior:'smooth',block:'start'});current=i;nav.forEach(x=>x.classList.toggle('active',+x.dataset.go===i));}
nav.forEach(b=>b.addEventListener('click',()=>go(+b.dataset.go)));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){current=+e.target.dataset.scene;nav.forEach(x=>x.classList.toggle('active',+x.dataset.go===current));e.target.classList.add('scene-live')}}),{threshold:.55});scenes.forEach(s=>obs.observe(s));
addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<28||locked)return;locked=true;go(current+(e.deltaY>0?1:-1));setTimeout(()=>locked=false,750)},{passive:true});
let sy=0;addEventListener('touchstart',e=>sy=e.touches[0].clientY,{passive:true});addEventListener('touchend',e=>{let dy=sy-e.changedTouches[0].clientY;if(Math.abs(dy)>55)go(current+(dy>0?1:-1))},{passive:true});
// ambient particles
const p=$('#particles');for(let i=0;i<110;i++){let el=document.createElement('i');el.className=i%5===0?'petal':'particle';el.style.left=Math.random()*100+'%';el.style.top=Math.random()*100+'%';el.style.setProperty('--d',(4+Math.random()*15)+'s');el.style.animationDelay=(-Math.random()*18)+'s';el.style.transform=`scale(${.3+Math.random()*1.4})`;p.appendChild(el)}
// paint
const pc=$('#paintCanvas');if(pc){const ctx=pc.getContext('2d');let pts=[];function resizePaint(){const d=devicePixelRatio||1;pc.width=pc.clientWidth*d;pc.height=pc.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)}resizePaint();addEventListener('resize',resizePaint);function paint(x,y){pts.push({x,y,t:performance.now()});if(pts.length>100)pts.shift()}pc.parentElement.addEventListener('pointermove',e=>{const r=pc.getBoundingClientRect();paint(e.clientX-r.left,e.clientY-r.top)});function draw(){ctx.clearRect(0,0,pc.clientWidth,pc.clientHeight);ctx.lineCap='round';for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],age=(performance.now()-b.t)/1800;if(age>1)continue;ctx.strokeStyle=`rgba(0,137,139,${(1-age)*.5})`;ctx.lineWidth=2+(1-age)*9;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}requestAnimationFrame(draw)}draw()}
// piano with white + black keys
const piano=$('#piano');let audioCtx=null;function tone(freq){audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.13,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.65);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.7)}
if(piano){const whites=[['C4',261.63],['D4',293.66],['E4',329.63],['F4',349.23],['G4',392],['A4',440],['B4',493.88],['C5',523.25],['D5',587.33],['E5',659.25],['F5',698.46],['G5',783.99],['A5',880],['B5',987.77]];const blacks=[['C#4',277.18,0],['D#4',311.13,1],['F#4',369.99,3],['G#4',415.3,4],['A#4',466.16,5],['C#5',554.37,7],['D#5',622.25,8],['F#5',739.99,10],['G#5',830.61,11],['A#5',932.33,12]];whites.forEach(([name,f])=>{const k=document.createElement('button');k.type='button';k.className='key white-key';k.textContent=name[0];k.setAttribute('aria-label',name);const play=()=>{tone(f);k.classList.add('play');setTimeout(()=>k.classList.remove('play'),140)};k.addEventListener('pointerdown',play);piano.appendChild(k)});blacks.forEach(([name,f,idx])=>{const k=document.createElement('button');k.type='button';k.className='key black-key';k.textContent='';k.dataset.after=idx;k.setAttribute('aria-label',name);k.addEventListener('pointerdown',()=>{tone(f);k.classList.add('play');setTimeout(()=>k.classList.remove('play'),140)});piano.appendChild(k)});}
// waveform
const wc=$('#waveCanvas');if(wc){const wx=wc.getContext('2d');let phase=0;function wave(){const d=devicePixelRatio||1;wc.width=wc.clientWidth*d;wc.height=wc.clientHeight*d;wx.setTransform(d,0,0,d,0,0);wx.clearRect(0,0,wc.clientWidth,wc.clientHeight);wx.beginPath();for(let x=0;x<wc.clientWidth;x++){const y=wc.clientHeight/2+Math.sin(x*.025+phase)*18+Math.sin(x*.071-phase*1.7)*8;if(x===0)wx.moveTo(x,y);else wx.lineTo(x,y)}wx.strokeStyle='#00898b';wx.lineWidth=2;wx.stroke();phase+=.035;requestAnimationFrame(wave)}wave()}
const sound=$('#soundBtn');if(sound)sound.addEventListener('click',()=>{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const on=!!window.__ambient;if(on){window.__ambient.stop();window.__ambient=null;sound.innerHTML='♫ <span>sound</span>'}else{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=130;g.gain.value=.015;o.connect(g).connect(audioCtx.destination);o.start();window.__ambient=o;sound.innerHTML='♫ <span>on</span>'}});
// Pointer parallax
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',(e.clientX/innerWidth-.5));document.documentElement.style.setProperty('--my',(e.clientY/innerHeight-.5))},{passive:true});
// Generic click-through work portals
$$('[data-link]').forEach(el=>el.addEventListener('click',e=>{if(el.matches('.model,.film-object,.skill-orb,.firefly,.flower-bed')){e.preventDefault();el.classList.add('selected');setTimeout(()=>location.href=el.dataset.link,180)}}));
// Reusable drag-to-rotate 3D scenes. Dragging never changes scroll position.
function makeRotatable(el,targets=[]){if(!el)return;let down=false,moved=false,sx=0,sy=0,rx=0,ry=0,lastX=0,lastY=0;const apply=()=>{el.style.setProperty('--rx',rx+'deg');el.style.setProperty('--ry',ry+'deg');targets.forEach(t=>{t.style.setProperty('--scene-rx',rx+'deg');t.style.setProperty('--scene-ry',ry+'deg')})};el.addEventListener('pointerdown',e=>{if(e.target.closest('a,button[data-link],.model,.film-object,.skill-orb,.firefly,.flower-bed')){down=true;lastX=e.clientX;lastY=e.clientY;return}down=true;moved=false;sx=e.clientX;sy=e.clientY;lastX=sx;lastY=sy;el.setPointerCapture?.(e.pointerId)});el.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(e.clientX-sx)+Math.abs(e.clientY-sy)>8)moved=true;ry+=dx*.38;rx=Math.max(-28,Math.min(28,rx-dy*.24));lastX=e.clientX;lastY=e.clientY;apply()});el.addEventListener('pointerup',()=>{down=false});el.addEventListener('pointercancel',()=>down=false);el.dataset.dragReady='true'}
makeRotatable($('#lab3d'),$$('.lab-orbit,#lab3d .model'));
makeRotatable($('#garden3d'),$$('.tree3d,.garden-moon,.flower-bed'));
makeRotatable($('#filmWorld'),$$('.film-environment,.film-object'));
const filmEnvs=$$('#filmWorld .film-environment');
filmEnvs.forEach(env=>{env.addEventListener('pointerenter',()=>{const r=$('#filmEnvReadout');if(r)r.textContent='WORLD · '+env.dataset.env.toUpperCase()+' · LIVE';});env.addEventListener('click',e=>{if(e.target.closest('button'))return;filmEnvs.forEach(x=>x.classList.remove('is-focus'));env.classList.add('is-focus');const r=$('#filmEnvReadout');if(r)r.textContent='CAMERA LOCK · '+env.dataset.env.toUpperCase()+' · DRAG TO EXPLORE';});});
makeRotatable($('#skillWorld'),[$('#skillJar3D')].filter(Boolean));
// Lab and garden status labels
$$('.model').forEach(m=>m.addEventListener('pointerenter',()=>{const s=$('#labStatus');if(s)s.textContent=m.getAttribute('title')+' · click to enter'}));
$$('.firefly,.flower-bed').forEach(m=>m.addEventListener('pointerenter',()=>{const s=$('#gardenStatus');if(s)s.textContent=m.getAttribute('title')+' · click to enter'}));
// Skill jar orbital motion
const orbs=$$('.skill-orb');let st=0;function animateSkills(){st+=.01;orbs.forEach((o,i)=>{if(o.matches(':hover,.selected'))return;const a=st*(i%2?-.7:.9)+i;const r=92+i%3*24;o.style.transform=`translate3d(${Math.cos(a)*r}px,${Math.sin(a)*r*.55}px,${Math.sin(a)*50}px) rotate(${a*18}deg)`});requestAnimationFrame(animateSkills)}animateSkills();
// Cards / image activation
const tiltTargets=$$('.card,.art-card,.photo-item,.edu-item,.project-card,.research-card,.journal-entry,.skill-card,.memory');tiltTargets.forEach(el=>{el.addEventListener('pointermove',e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5,amount=el.classList.contains('card')?2.2:5;el.style.transform=`perspective(900px) rotateX(${-y*amount}deg) rotateY(${x*amount}deg) translateY(-2px)`});el.addEventListener('pointerleave',()=>el.style.transform='');el.addEventListener('click',e=>{if(e.target.closest('a,button,input,textarea,select'))return;el.classList.add('ll-activated');setTimeout(()=>el.classList.remove('ll-activated'),450)})});
// Click ripple
addEventListener('pointerdown',e=>{if(e.target.closest('a,button'))return;const r=document.createElement('i');r.className='ll-ripple';r.style.left=e.clientX+'px';r.style.top=e.clientY+'px';document.body.append(r);setTimeout(()=>r.remove(),850)});
// Procedural cinematic engine: every scene gets its own evolving math/physics layer.
const sceneNames=['UNIVERSE','RESEARCH LAB','VISUAL ART','MUSIC ROOM','FILM WORLD','MEMORY GARDEN','EDUCATION','SKILL JAR','CONNECT'];
const equations=['e^{iπ}+1=0','∇·E=ρ/ε₀','y=A·sin(kx−ωt)','fₙ=n²f₀','x(t)=A cos(ωt+φ)','P(memory|time)','∑ᵢ wᵢxᵢ → insight','Σ tools → one system','science × art × story'];
let engineTime=0, lastScene=-1, frameCount=0;
const hud=document.createElement('div');hud.className='cinematic-hud';hud.innerHTML='<b id="hudScene">UNIVERSE</b><span id="hudMetric">frame 000000 · 60 fps</span><span class="hud-formula" id="hudEq">e^{iπ}+1=0</span>';document.body.append(hud);
function addSceneEngine(scene){
  if(scene.querySelector('.scene-engine')) return;
  const wrap=document.createElement('div');wrap.className='scene-engine';
  const c=document.createElement('canvas');wrap.appendChild(c);scene.prepend(wrap);
  const read=document.createElement('div');read.className='engine-readout';read.innerHTML='<strong>LIVE SIMULATION</strong><span>state: initializing</span><br><span>energy: 0.00</span>';
  scene.appendChild(read);scene._engine={c,ctx:c.getContext('2d'),read,phase:Math.random()*6.28,points:[]};
}
scenes.forEach(addSceneEngine);
function sizeEngine(st){const r=st.c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);st.c.width=Math.max(1,r.width*d);st.c.height=Math.max(1,r.height*d);st.ctx.setTransform(d,0,0,d,0,0);st.w=r.width;st.h=r.height}
function drawEngine(scene,idx,t){const st=scene._engine;if(!st)return; if(!st.w)sizeEngine(st);const {ctx,w,h}=st;ctx.clearRect(0,0,w,h);const live=scene.classList.contains('scene-live');const p=st.phase+t*.0007;
  ctx.save();
  if(idx===0){for(let i=0;i<90;i++){const a=i*.73+p*.35,r=35+(i%12)*18+Math.sin(p+i)*12,x=w*.72+Math.cos(a)*r,y=h*.47+Math.sin(a)*r*.58;ctx.fillStyle=`rgba(0,137,139,${.08+(i%5)*.025})`;ctx.beginPath();ctx.arc(x,y,1+(i%3),0,Math.PI*2);ctx.fill()}ctx.strokeStyle='rgba(255,172,5,.22)';ctx.beginPath();for(let x=0;x<w;x+=4){const y=h*.72+Math.sin(x*.014+p)*18+Math.sin(x*.031-p*1.8)*7;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();}
  if(idx===1){for(let j=0;j<4;j++){ctx.strokeStyle=j%2?'rgba(255,107,107,.22)':'rgba(85,255,249,.22)';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<w;x+=5){const y=h*(.2+j*.18)+Math.sin(x*.018+p*(1+j*.22)+j)*18; x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}for(let i=0;i<18;i++){const a=p*.8+i*.35,r=80+i*9;ctx.fillStyle='rgba(255,172,5,.32)';ctx.beginPath();ctx.arc(w*.5+Math.cos(a)*r,h*.45+Math.sin(a)*r*.45,2.5,0,Math.PI*2);ctx.fill()}}
  if(idx===2){ctx.globalAlpha=.32;for(let i=0;i<9;i++){ctx.strokeStyle=i%2?'#ff6b6b':'#00898b';ctx.lineWidth=1+i*.3;ctx.beginPath();for(let x=0;x<w;x+=6){const y=h*.5+Math.sin(x*.012+i*.8+p)*((18+i*5));x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}ctx.globalAlpha=1;}
  if(idx===3){ctx.strokeStyle='rgba(0,137,139,.3)';ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<w;x+=4){const y=h*.5+Math.sin(x*.025+p*3)*25+Math.sin(x*.071-p*4)*9;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();}
  if(idx===4){const horizon=h*.55;ctx.strokeStyle='rgba(255,255,255,.12)';for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(w*.5,horizon);ctx.lineTo(i*w/7, h);ctx.stroke()}for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(w*.5,horizon);ctx.lineTo(w-i*w/7,h);ctx.stroke()}ctx.fillStyle='rgba(255,246,201,.2)';ctx.beginPath();ctx.arc(w*.76,h*.18,34+Math.sin(p)*3,0,Math.PI*2);ctx.fill();}
  if(idx===5){for(let i=0;i<45;i++){const a=p*.2+i*1.7,x=(w*(.15+.7*((i*37)%100)/100)+Math.sin(p+i)*20)%w,y=h*(.2+.65*((i*17)%100)/100)+Math.cos(p*.8+i)*18;ctx.fillStyle=`rgba(255,236,147,${.08+(i%4)*.04})`;ctx.beginPath();ctx.arc(x,y,1.5+(i%3),0,Math.PI*2);ctx.fill()}}
  if(idx===6){ctx.strokeStyle='rgba(0,137,139,.15)';for(let i=0;i<10;i++){ctx.beginPath();ctx.moveTo(w*.08+i*w*.09,0);ctx.lineTo(w*.02+i*w*.1,h);ctx.stroke()}}
  if(idx===7){const cx=w*.5,cy=h*.52;for(let i=0;i<24;i++){const a=p*(i%2?-.55:.8)+i*.262,r=45+(i%5)*22;ctx.strokeStyle=i%3?'rgba(85,255,249,.16)':'rgba(255,172,5,.22)';ctx.beginPath();ctx.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r*.55,2+(i%3),0,Math.PI*2);ctx.stroke()}}
  if(idx===8){for(let i=0;i<14;i++){const a=p*.18+i*Math.PI*2/14,r=70+Math.sin(p+i)*14;ctx.strokeStyle='rgba(85,255,249,.12)';ctx.beginPath();ctx.moveTo(w*.5,h*.45);ctx.lineTo(w*.5+Math.cos(a)*r,h*.45+Math.sin(a)*r);ctx.stroke()}}
  ctx.restore();
  const energy=(.5+.5*Math.sin(t*.0017+idx))*100;st.read.querySelector('span:nth-of-type(1)').textContent=`state: ${live?'interactive':'waiting'}`;st.read.querySelector('span:nth-of-type(2)').textContent=`energy: ${energy.toFixed(1)}%`;
}
addEventListener('resize',()=>scenes.forEach(s=>s._engine&&sizeEngine(s)),{passive:true});
function engineLoop(t){engineTime=t;frameCount++;const idx=current;scenes.forEach((s,i)=>{if(s._engine)drawEngine(s,i,t)});const hs=$('#hudScene'),hm=$('#hudMetric'),he=$('#hudEq');if(hs)hs.textContent=sceneNames[idx]||'SCENE';if(hm)hm.textContent=`frame ${String(frameCount%1000000).padStart(6,'0')} · live`;if(he)he.textContent=equations[idx]||equations[0];requestAnimationFrame(engineLoop)}requestAnimationFrame(engineLoop);
// Scene-specific interaction upgrades.
const turbine=$('.model-turbine');let turbineSpeed=3;if(turbine){turbine.addEventListener('pointermove',e=>{const r=turbine.getBoundingClientRect(),v=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));turbineSpeed=1.2+v*4;turbine.querySelectorAll('.blade').forEach(b=>b.style.animationDuration=turbineSpeed.toFixed(2)+'s');const s=$('#labStatus');if(s)s.textContent=`wind speed ${(2+v*12).toFixed(1)} m/s · blade period ${turbineSpeed.toFixed(2)} s`})}
const waveModel=$('.model-wave');if(waveModel){waveModel.addEventListener('pointermove',e=>{const r=waveModel.getBoundingClientRect(),v=(e.clientY-r.top)/r.height;waveModel.querySelector('.wave-ring').style.animationDuration=(.65+v*1.7).toFixed(2)+'s';const s=$('#labStatus');if(s)s.textContent=`vibration mode ${(1+Math.round(v*5))} · damping ${(1-v).toFixed(2)}`})}
const chess=$('.model-chess');if(chess){let q=0;chess.addEventListener('pointermove',e=>{q+=e.movementX||0;chess.style.transform=`rotateY(${q*.9}deg) rotateX(${-(e.movementY||0)*.8}deg) scale(1.12)`})}
const artStage=$('.brush-stage');if(artStage){let dots=[];artStage.addEventListener('pointermove',e=>{const r=artStage.getBoundingClientRect();dots.push({x:e.clientX-r.left,y:e.clientY-r.top,t:performance.now()});if(dots.length>90)dots.shift();});}
const pianoKeys=$$('#piano .key');pianoKeys.forEach(k=>k.addEventListener('pointerdown',()=>{document.body.style.setProperty('--music-hit',Math.random().toFixed(2));const f=equations[3];const he=$('#hudEq');if(he)he.textContent=`${f} · note ${k.getAttribute('aria-label')}`}));
const skillWorld=$('#skillWorld');if(skillWorld){let energy=0;skillWorld.addEventListener('pointermove',e=>{energy=Math.min(100,Math.abs(e.movementX||0)*2+energy*.92);skillWorld.style.setProperty('--skill-energy',energy);const hs=$('#hudMetric');if(hs)hs.textContent=`tool energy ${energy.toFixed(0)}% · live`;});}
// keyboard travel
addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,[contenteditable=true]'))return;const k=e.key.toLowerCase();if(k==='arrowdown'||k==='pagedown')go(current+1);if(k==='arrowup'||k==='pageup')go(current-1);if(k==='h')location.href='index.html';if(k==='c')window.open('Lisa-Liu-CV.pdf','_blank');if(k==='m')location.href='music.html';if(k==='w')location.href='research.html';});
})();


